"""Update schema

Revision ID: 32ce033d843f
Revises: ccee2d890052
Create Date: 2025-07-07 15:29:51.757672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32ce033d843f'
down_revision: Union[str, Sequence[str], None] = 'ccee2d890052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('segment', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'segment', ['track_id'])
    op.drop_constraint(op.f('segment_track_id_fkey'), 'segment', type_='foreignkey')
    op.create_foreign_key(None, 'segment', 'track', ['track_id'], ['id'], ondelete='CASCADE')
    op.drop_column('segment', 'pitch_7')
    op.drop_column('segment', 'confidence')
    op.drop_column('segment', 'timbre_6')
    op.drop_column('segment', 'timbre_5')
    op.drop_column('segment', 'timbre_1')
    op.drop_column('segment', 'timbre_9')
    op.drop_column('segment', 'timbre_11')
    op.drop_column('segment', 'timbre_2')
    op.drop_column('segment', 'pitch_10')
    op.drop_column('segment', 'timbre_3')
    op.drop_column('segment', 'timbre_4')
    op.drop_column('segment', 'pitch_6')
    op.drop_column('segment', 'pitch_4')
    op.drop_column('segment', 'pitch_1')
    op.drop_column('segment', 'timbre_7')
    op.drop_column('segment', 'pitch_2')
    op.drop_column('segment', 'segment_index')
    op.drop_column('segment', 'timbre_0')
    op.drop_column('segment', 'timbre_10')
    op.drop_column('segment', 'pitch_8')
    op.drop_column('segment', 'pitch_3')
    op.drop_column('segment', 'pitch_0')
    op.drop_column('segment', 'pitch_5')
    op.drop_column('segment', 'pitch_11')
    op.drop_column('segment', 'pitch_9')
    op.drop_column('segment', 'timbre_8')
    op.drop_column('segment', 'loudness_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('loudness_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_8', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_9', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_11', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_0', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_8', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_10', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_0', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('segment_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('segment', sa.Column('pitch_2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_7', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_6', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_10', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_11', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_9', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre_6', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch_7', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'segment', type_='foreignkey')
    op.create_foreign_key(op.f('segment_track_id_fkey'), 'segment', 'track', ['track_id'], ['id'])
    op.drop_constraint(None, 'segment', type_='unique')
    op.alter_column('segment', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('segment', 'segments')
    # ### end Alembic commands ###
