"""Update schema

Revision ID: 42f3fd2dc955
Revises: a6b6ffc8548c
Create Date: 2025-07-13 12:39:04.784163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f3fd2dc955'
down_revision: Union[str, Sequence[str], None] = 'a6b6ffc8548c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'artist_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=400),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'artist_name',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
