"""Update schema

Revision ID: 80a15e686bce
Revises: 32ce033d843f
Create Date: 2025-07-07 22:14:09.873360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a15e686bce'
down_revision: Union[str, Sequence[str], None] = '32ce033d843f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('segment_index', sa.Integer(), nullable=False))
    op.add_column('segment', sa.Column('loudness_max', sa.Float(), nullable=True))
    op.add_column('segment', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('segment', sa.Column('pitch', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('segment', sa.Column('timbre', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('segment', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_segment_id'), table_name='segment')
    op.drop_constraint(op.f('segment_track_id_key'), 'segment', type_='unique')
    op.drop_constraint(op.f('segment_track_id_fkey'), 'segment', type_='foreignkey')
    op.create_foreign_key(None, 'segment', 'track', ['track_id'], ['id'])
    op.drop_column('segment', 'segments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'segment', type_='foreignkey')
    op.create_foreign_key(op.f('segment_track_id_fkey'), 'segment', 'track', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('segment_track_id_key'), 'segment', ['track_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_segment_id'), 'segment', ['id'], unique=False)
    op.alter_column('segment', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('segment', 'timbre')
    op.drop_column('segment', 'pitch')
    op.drop_column('segment', 'confidence')
    op.drop_column('segment', 'loudness_max')
    op.drop_column('segment', 'segment_index')
    # ### end Alembic commands ###
