"""Update schema

Revision ID: 83e8c475f209
Revises: ac6e31692760
Create Date: 2025-07-07 22:45:10.826219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83e8c475f209'
down_revision: Union[str, Sequence[str], None] = 'ac6e31692760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('segment', 'segment_index')
    op.drop_column('segment', 'confidence')
    op.drop_column('segment', 'timbre')
    op.drop_column('segment', 'pitch')
    op.drop_column('segment', 'loudness_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('loudness_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('pitch', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('timbre', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('segment', sa.Column('segment_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('segment', 'segments')
    # ### end Alembic commands ###
