"""Initial schema

Revision ID: ccee2d890052
Revises: 
Create Date: 2025-07-07 13:57:37.728814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccee2d890052'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_name')
    )
    op.create_index(op.f('ix_artist_id'), 'artist', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('artist_familiarity', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_track_id'), 'track', ['id'], unique=False)
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('timbre_0', sa.Float(), nullable=True),
    sa.Column('timbre_1', sa.Float(), nullable=True),
    sa.Column('timbre_2', sa.Float(), nullable=True),
    sa.Column('timbre_3', sa.Float(), nullable=True),
    sa.Column('timbre_4', sa.Float(), nullable=True),
    sa.Column('timbre_5', sa.Float(), nullable=True),
    sa.Column('timbre_6', sa.Float(), nullable=True),
    sa.Column('timbre_7', sa.Float(), nullable=True),
    sa.Column('timbre_8', sa.Float(), nullable=True),
    sa.Column('timbre_9', sa.Float(), nullable=True),
    sa.Column('timbre_10', sa.Float(), nullable=True),
    sa.Column('timbre_11', sa.Float(), nullable=True),
    sa.Column('pitch_0', sa.Float(), nullable=True),
    sa.Column('pitch_1', sa.Float(), nullable=True),
    sa.Column('pitch_2', sa.Float(), nullable=True),
    sa.Column('pitch_3', sa.Float(), nullable=True),
    sa.Column('pitch_4', sa.Float(), nullable=True),
    sa.Column('pitch_5', sa.Float(), nullable=True),
    sa.Column('pitch_6', sa.Float(), nullable=True),
    sa.Column('pitch_7', sa.Float(), nullable=True),
    sa.Column('pitch_8', sa.Float(), nullable=True),
    sa.Column('pitch_9', sa.Float(), nullable=True),
    sa.Column('pitch_10', sa.Float(), nullable=True),
    sa.Column('pitch_11', sa.Float(), nullable=True),
    sa.Column('loudness_max', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_id'), 'segment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_id'), table_name='segment')
    op.drop_table('segment')
    op.drop_index(op.f('ix_track_id'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_artist_id'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
